# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: code-dds
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf-8&useSSL=false&useAffectedRows=true&allowMultiQueries=true
      username: root
      password: zbl5337
      driver-class-name: com.mysql.cj.jdbc.Driver
    master2:
      jdbc-url: jdbc:mysql://localhost:3306/test2?characterEncoding=utf-8&useSSL=false&useAffectedRows=true&allowMultiQueries=true
      username: root
      password: zbl5337
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/test2?characterEncoding=utf-8&useSSL=false&useAffectedRows=true&allowMultiQueries=true
      username: root
      password: zbl5337
      driver-class-name: com.mysql.cj.jdbc.Driver
#dds:
#  mapperIds:
#    com.zbl.mapper.UserMapper.findAll
server:
  port: 7999





